### ISSUE TITLE
Running in Node problem

### ISSUE THREAD

**Issue by ondratra** [bitpay/bitcore-lib#114]
Hi, 
when i setup simple project via: (yarn could be replaced by npm)
`yarn add --dev bitcore-message bitcore-lib`

write simple test to index.js file:
```
"use strict"

var BitcoreMessage = require('bitcore-message');
var BitcoreLib = require('bitcore-lib');

var privateKeyObject = new BitcoreLib.PrivateKey();
var message = new BitcoreMessage('MessageToBeSigned');
var signedMessage = message.sign(privateKeyObject)

console.log(signedMessage)
```

and then run it: (my nodejs version is v7.1.0)
`nodejs index.js`

i end up with this error

```
var b2 = this.r.toBuffer({
                  ^

TypeError: this.r.toBuffer is not a function
    at Signature.toCompact (/mnt/work/3rdParty/bitcore-lib/node_modules/bitcore-lib/lib/crypto/signature.js:158:19)
    at Message.sign (/mnt/work/3rdParty/bitcore-lib/node_modules/bitcore-message/lib/message.js:63:20)
    at Object.<anonymous> (/mnt/work/3rdParty/bitcore-lib/tmp.js:10:29)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
```

It seems to me like some broken dependency or broken recognition of browser/node environment. It's trivial example inspired by official documentation. Does anybody know what's wrong?

**Comment by ondratra** [comment]
Nevermind. I found out that problem was actually in yarn - in older versions(<0.17) there was bug causing package dependency malufanction. More information about change can be found in this issue https://github.com/yarnpkg/yarn/issues/1933
