### ISSUE TITLE
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.

### ISSUE THREAD

**Issue by gkucmierz** [bitpay/bitcore-lib#153]
This repository shows the problem:

https://github.com/gkucmierz/bitcore-test

```
/Users/gkucmierz/learn/bitcore-test/node_modules/bitcore-message/node_modules/bitcore-lib/index.js:12
    throw new Error(message);
    ^

Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/Users/gkucmierz/learn/bitcore-test/node_modules/bitcore-message/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/Users/gkucmierz/learn/bitcore-test/node_modules/bitcore-message/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/gkucmierz/learn/bitcore-test/node_modules/bitcore-message/index.js:1:77)
```

**Comment by Sexual** [comment]
Add `delete global._bitcore;` before you require bitcore-lib

**Comment by gkucmierz** [comment]
https://github.com/gkucmierz/bitcore-test/commit/50de2ba949eb0aab1b7213335ebec449079a6d6b

Thanks for your time, looks like it is forking.

**Comment by Levino** [comment]
Welcome to bitcore-lib. This issue is an ever annoying one that wontfix: https://github.com/bitpay/bitcore-lib/issues/21

**Comment by AlexanderKozhevin** [comment]
Restarting the server helped me.

**Comment by JamesJansson** [comment]
@Sexual 
> Try googling next time because this is a common issue.

Yeah, so this solution does NOT come up when Googling. This is the fourth issue on Google for me.  Lucky I came across your comment, because it saved me, but the fact that:

1) It is not documented
2) This behavior exists in the first place 

is annoying.
