### ISSUE TITLE
Bitcoin Height: 498766 Percentage: 99.72 .  : Error: number too large to retain precision - use readVarintBN

### ISSUE THREAD

**Issue by cryptogear** [bitpay/bitcore-lib#182]
[2017-12-14T17:41:28.635Z] info: Using config: /root/mynode/bitcore-node.json
[2017-12-14T17:41:28.637Z] info: Using network: livenet
[2017-12-14T17:41:28.637Z] info: Starting bitcoind
[2017-12-14T17:41:28.639Z] info: Using bitcoin config file: /root/.bitcoin/bitcoin.conf
[2017-12-14T17:41:28.641Z] info: Starting bitcoin process
[2017-12-14T17:41:33.674Z] warn: Rewinding blocks...
[2017-12-14T17:41:52.677Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
[2017-12-14T17:41:52.678Z] info: ZMQ connected to: tcp://127.0.0.1:28332
[2017-12-14T17:41:54.064Z] info: Bitcoin Height: 498766 Percentage: 99.72
[2017-12-14T17:42:28.647Z] info: Bitcoin Daemon Ready
[2017-12-14T17:42:28.647Z] info: Starting web
[2017-12-14T17:42:28.666Z] info: Starting insight-api
[2017-12-14T17:42:28.667Z] info: Bitcoin Height: 498786 Percentage: 99.76
[2017-12-14T17:42:28.668Z] info: Starting insight-ui
[2017-12-14T17:42:28.668Z] info: Bitcore Node ready
[2017-12-14T17:42:34.647Z] info: ::ffff:zzzzz web socket subscribe: inv
[2017-12-14T17:42:34.810Z] info: ::ffff:zzzzz web socket subscribe: inv
[2017-12-14T17:42:34.811Z] info: ::ffff:zzzzzz web socket subscribe: sync
[2017-12-14T17:42:43.128Z] info: Bitcoin Height: 498842 Percentage: 99.76
[2017-12-14T17:42:43.512Z] info: ::ffff:ZZZZZZ "GET /insight-api/blocks?limit=5" 400 29 4.151 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" 
[2017-12-14T17:43:09.070Z] error: uncaught exception: Error: number too large to retain precision - use readVarintBN
    at BufferReader.readVarintNum (/root/mynode/node_modules/bitcore-lib/lib/encoding/bufferreader.js:133:15)
    at BufferReader.readVarLengthBuffer (/root/mynode/node_modules/bitcore-lib/lib/encoding/bufferreader.js:145:18)
    at Function.Input.fromBufferReader (/root/mynode/node_modules/bitcore-lib/lib/transaction/input/input.js:95:28)
    at Transaction.fromBufferReader (/root/mynode/node_modules/bitcore-lib/lib/transaction/transaction.js:307:23)
    at Function._fromBufferReader (/root/mynode/node_modules/bitcore-lib/lib/block/block.js:92:42)
    at Function.fromBufferReader (/root/mynode/node_modules/bitcore-lib/lib/block/block.js:103:20)
    at Function.fromBuffer (/root/mynode/node_modules/bitcore-lib/lib/block/block.js:112:16)
    at Function.fromString (/root/mynode/node_modules/bitcore-lib/lib/block/block.js:121:16)
    at /root/mynode/node_modules/bitcore-node/lib/services/bitcoind.js:1686:40
    at IncomingMessage.<anonymous> (/root/mynode/node_modules/bitcoind-rpc/lib/index.js:107:7)

**Comment by sunnyFrank** [comment]
do you solve this problem  i got this problem too

**Comment by wangluen** [comment]
do not go to the url: http://localhost:3001/insight/
and I bypass this problem

**Comment by xelawafs** [comment]
@wangluen sorry, I didn't get the solution you proposed. What did you do to solve this problem?

**Comment by Lalitpatadiya12** [comment]
I also got the same issue, guys any solution?

**Comment by phongnguyen91** [comment]
I got the same issue. Hope to see any solution ^^!
