### ISSUE TITLE
Address.createMultiSig crashing bitcored

### ISSUE THREAD

**Issue by chrisrico** [bitpay/bitcore-lib#39]
Stack trace (I'm not sure how to enable debug logging through bitcored):
```
[2016-02-01T09:26:42.984Z] error: uncaught exception: [TypeError: value is out of bounds]
[2016-02-01T09:26:42.985Z] error: TypeError: value is out of bounds
    at checkInt (buffer.js:832:11)
    at Buffer.writeUInt8 (buffer.js:880:5)
    at BufferWriter.writeUInt8 (/usr/local/lib/node_modules/bitcore/node_modules/bitcore-lib/lib/encoding/bufferwriter.js:42:7)
    at Script.toBuffer (/usr/local/lib/node_modules/bitcore/node_modules/bitcore-lib/lib/script/script.js:115:8)
    at Function.Address.payingTo (/usr/local/lib/node_modules/bitcore/node_modules/bitcore-lib/lib/address.js:338:61)
    at Function.Address.createMultisig (/usr/local/lib/node_modules/bitcore/node_modules/bitcore-lib/lib/address.js:262:18)
    at Function.Address._deriveAddress (/usr/local/lib/node_modules/bitcore/node_modules/bitcore-wallet-service/lib/model/address.js:56:40)
    at Function.Address.derive (/usr/local/lib/node_modules/bitcore/node_modules/bitcore-wallet-service/lib/model/address.js:72:21)
    at Wallet.createAddress (/usr/local/lib/node_modules/bitcore/node_modules/bitcore-wallet-service/lib/model/wallet.js:163:25)
    at /usr/local/lib/node_modules/bitcore/node_modules/bitcore-wallet-service/lib/server.js:794:30
```

I logged the arguments to Address.payingTo:
```
{script: {"chunks":[{"opcodenum":811},{"buf":{"type":"Buffer","data":[3,163,137,15,87,90,60,52,224,236,237,246,169,152,207,194,129,181,154,200,230,159,237,199,174,83,199,124,32,251,110,89,69]},"len":33,"opcodenum":33},{"buf":{"type":"Buffer","data":[3,245,49,194,114,40,23,63,79,95,17,138,169,108,122,43,31,21,197,244,45,82,189,218,47,60,247,214,88,133,216,23,190]},"len":33,"opcodenum":33},{"opcodenum":82},{"opcodenum":174}]}, network: 'livenet'}
```

It's ultimately failing on the call to bw.writeUInt8 with this chunk:
```
{ opcodenum: 811 }
```

**Comment by braydonf** [comment]
Looks like this is a string concatenation instead of addition bug in `Opcode.smallInt` https://github.com/bitpay/bitcore-lib/blob/master/lib/script/script.js#L673:

```
> 81 + '2' - 1
811
```

@matiu @isocolsky

**Comment by braydonf** [comment]
Running the tests for bitcore-wallet-service (https://github.com/bitpay/bitcore-wallet-service/commit/65a6ce4e8a4ddcabf7680269e71316d7b30382d6) and "m" is an integer, so it's not clear where the string value for "m" is coming from.

**Comment by chrisrico** [comment]
Is there anything I can provide to help debug the issue, or are you able to replicate it on your end?

**Comment by matiu** [comment]
ACK with the extra validation at:

https://github.com/bitpay/bitcore-lib/pull/40/files


It seem very string forward  from:

at Wallet.createAddress (/usr/local/lib/node_modules/bitcore/node_modules/bitcore-wallet-service/lib/model/wallet.js:163:25

that the parameter `m` comes from the wallet.

Could you add a log at ` Wallet.createAddress` with `this` contents?
Also, checking the data of the wallet stored on mongoDB would help.

**Comment by chrisrico** [comment]
In Wallet.createAddress, 'this' references a Wallet with the following data:

```
{"version":"1.0.0","createdOn":1454342778,"id":"595ae5e0-437f-495e-8b8d-571378ac5125","name":"Test","m":"2","n":"2","status":"complete","publicKeyRing":[{"xPubKey":"xpub6C1SxTfJCGoVJMDtRDbqyCdF4AdbfvjzqyKz5ay5ktF6c71Poqb77zj44SpKwxnvye7pNL9ZpWr8KkweG9DFNKunEMNkQsieCrgAVvDxAF7","requestPubKey":"036a898bdd4c090b19d4d81346d5ec63b1ace7ac27e5924ddab614fb0fcc6ef9e6"},{"xPubKey":"xpub6CXzZMqEHytjZcydfRwHfsJaiKGt1iCVf5RsiWM4FUJQdAX2z8U87vvGxT6RfVqGgZiPjuKUxEGz1WZcLfT1Dwanw2QZiKnDJKoLPRTguSB","requestPubKey":"02cc8e6c92dec02d7459eeb44bb543516e11f58ac3c6ab4b1c364153100a55c6dc"}],"copayers":[{"version":2,"createdOn":1454342778,"id":"fd5d9b1dfbbabb25962ad42d22d8de02c5855fe749c00580a66cea178fcb6dcd","name":"BATM Server","xPubKey":"xpub6C1SxTfJCGoVJMDtRDbqyCdF4AdbfvjzqyKz5ay5ktF6c71Poqb77zj44SpKwxnvye7pNL9ZpWr8KkweG9DFNKunEMNkQsieCrgAVvDxAF7","requestPubKey":"036a898bdd4c090b19d4d81346d5ec63b1ace7ac27e5924ddab614fb0fcc6ef9e6","signature":"304402207c5346eef980172954c40151b7b46e86962b3a957aca60472364e4c1b75e6e5d02207c66abb1b998bd5750308acfa4d410f8e5a14592b1b0f1bedb40cee1deab2741","requestPubKeys":[{"key":"036a898bdd4c090b19d4d81346d5ec63b1ace7ac27e5924ddab614fb0fcc6ef9e6","signature":"304402207c5346eef980172954c40151b7b46e86962b3a957aca60472364e4c1b75e6e5d02207c66abb1b998bd5750308acfa4d410f8e5a14592b1b0f1bedb40cee1deab2741"}],"customData":"{\\"iv\\":\\"wdZowfrc7r9RHq2xrQQlrg==\\",\\"v\\":1,\\"iter\\":1,\\"ks\\":128,\\"ts\\":64,\\"mode\\":\\"ccm\\",\\"adata\\":\\"\\",\\"cipher\\":\\"aes\\",\\"ct\\":\\"DAdKsbUGugOUv49DYEEevAnuSJi7anCv9jmFseDavIAWNeXsbjStxrjhNiqGtDeIi/2mAL28NFMRbjY6n/Vd/VonmKzSxq1E3Stck8vltZIlEs6tDmIXsr/MffA=\\"}"},{"version":2,"createdOn":1454342804,"id":"2f85989408b7ba7a089a8944f3f4f2fea6a4b18d7cf036e98f03247c6a1652c1","name":"Chris","xPubKey":"xpub6CXzZMqEHytjZcydfRwHfsJaiKGt1iCVf5RsiWM4FUJQdAX2z8U87vvGxT6RfVqGgZiPjuKUxEGz1WZcLfT1Dwanw2QZiKnDJKoLPRTguSB","requestPubKey":"02cc8e6c92dec02d7459eeb44bb543516e11f58ac3c6ab4b1c364153100a55c6dc","signature":"304402207dcbfd449a2709d48cbf7cd80b9b83f27bf6acdfe69b48640c89028c1ef7701f0220509c05f6b054d6f8e35f945f815d6db743cf78324eb4219715e7788d762242a4","requestPubKeys":[{"key":"02cc8e6c92dec02d7459eeb44bb543516e11f58ac3c6ab4b1c364153100a55c6dc","signature":"304402207dcbfd449a2709d48cbf7cd80b9b83f27bf6acdfe69b48640c89028c1ef7701f0220509c05f6b054d6f8e35f945f815d6db743cf78324eb4219715e7788d762242a4"}],"customData":"{\\"iv\\":\\"6QM6FjQpm5ypkhhby11a7w==\\",\\"v\\":1,\\"iter\\":1,\\"ks\\":128,\\"ts\\":64,\\"mode\\":\\"ccm\\",\\"adata\\":\\"\\",\\"cipher\\":\\"aes\\",\\"ct\\":\\"3e+cLBSP0JXfxKOVM7smIbVYp9HQXzfBRwzJSU+y6i7DpJtt8+fdtJFsBvnnxpgSFfNB0qBwj/iVN1uAwdJVwadlRhumvE0nMNsIbMVDPpJD16qvuHNUB7sABbc=\\"}"}],"pubKey":"0358aa135cfe482380371a7065075e55eeae913d48b48d016dcdf1a96424fdb869","network":"livenet","derivationStrategy":"BIP44","addressType":"P2SH","addressManager":{"version":2,"derivationStrategy":"BIP44","receiveAddressIndex":0,"changeAddressIndex":0,"copayerIndex":2147483647},"scanStatus":"running"}
```

I'm not sure how to check the data in MongoDB, but if you can point me in the right direction I'll get it for you. I can also just send you the wallet if that's easier, I created it just for testing, it has no funds.

**Comment by braydonf** [comment]
"m" and "n" are indeed both strings there.

**Comment by chrisrico** [comment]
Ok, then it's probably because I'm creating it with those parameters on the client as strings. I'll parse them to integers first. I'm using the bitcore-wallet-client library, I would have expected it to verify that.

**Comment by matiu** [comment]
thanks a lot for update.

On Mon, Feb 1, 2016 at 1:14 PM, Chris Rico <notifications@github.com> wrote:

> Ok, then it's probably because I'm creating it with those parameters on
> the client as strings. I'll parse them to integers first. I'm using the
> bitcore-wallet-client library, I would have expected it to verify that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-lib/issues/39#issuecomment-178048803>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by chrisrico** [comment]
Just to confirm, when I ensure "m" and "n" are numbers when creating the wallet, the error does not occur.
